name: Ping Supabase API

on:
  schedule:
    - cron: '0 0 */2 * *'  # Runs every 2 days
  workflow_dispatch:  # Allows manual triggering

jobs:
  ping-api:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Supabase API
        run: |
          curl -X GET "https://acfwjcgwlkveknfqthsn.supabase.co/rest/v1/users" \
          -H "apikey: ${{ secrets.SUPABASE_API_KEY }}"
